%YAML:1.0

# Bag Info
preRectified: 1
startTime: 8
bagPath: "/home/ubuntu/dataset/kitti-odom/05/"
lidarPath: "/media/ygling2008/DATA/KITTI/lidar/05/velodyne/"
gtPoseFile: "/home/ubuntu/dataset/kitti-odom/groundtruth_poses/05.txt"
imageTotalNum: 2760
flipStereo: 0

# Debug Info
displayViewer: 1

# Mesh parameters
renderingK: 5
displayDelaunyResult: 1
displayCenterFrame: 1
displayUnOptimizedPoints: 0
meshSubdivNum: 0
cvWaitTime: 1
#pointQualityThreshold: 0
pointQualityThreshold: 0.01
#pointUpdateThreshold: 1
pointUpdateThreshold: 0.1
#constraintUpdateThreshold: 1.5
constraintUpdateThreshold: 0.2
#distanceThreshold: 0.3
distanceThreshold: 0.3

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 707.0912
Camera.fy: 707.0912
Camera.cx: 601.8873
Camera.cy: 183.1104

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

# Camera frames per second 
Camera.fps: 10.0

# stereo baseline times fx
Camera.bf: 379.8145

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.MeshLineWidth: 0.8
Viewer.PointSize: 2
Viewer.CameraSize: 0.3
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: 0
Viewer.ViewpointZ: -10
Viewer.ViewpointF: 707.0912



